### PR TITLE
Update class.swpm-admin-registration.php

### PR DESCRIPTION
**Pull request by MedTR-git**
When admin adds a member, dont change default WordPress display name format (first_name last_name).
check if first name and last name are sets, use default format otherwise use username as display name.

### CODE REVIEW

**Review by MedTR-git — COMMENTED** [review]
user !empty() rather than isset() to prevent an "empty" display name

**Comment by wp-insider** [comment]
This is not a good change given the history of our plugin. The core plugin allows the members to register without any first name or last name. We don't want all those installs to not have a display name value at all.

Rather than changing the existing behavior that is being used on tens of thousands of sites, you can add a filter hook for the display name (or request us to add an appropriate filter hook there).  The filter hook will then allow you to customize the behavior on your site without affecting other sites.

**Comment by MedTR-git** [comment]
yep, i think a filter hook will be the best solution.
so consider adding it please.
thank you :)

**Comment by wp-insider** [comment]
Thank you. I will add the following filter hook to the plugin.

swpm_admin_end_registration_display_name

**Pull request closed without merging**
