### PR TITLE
Added option 'use-automatic-username' to be able to enable/disable the automatic username generation

### PR DESCRIPTION
**Pull request by Th0masL**
Hi,

In this PR I've added an option that allow to automatically generate the usernames.

When enabled, the usernames will be automatically populated by the plugin, and the field "username" will be hidden on the User Creation and User Edit form.

The format of the automatically generated usernames is based on the current date/time + a 4 digit long random number : YYMMDDHHmmXXXX

Example for an user creating an account on July 25th 2020 at 8:55 AM : 20072508551234

Thanks

Thomas

### CODE REVIEW

**Comment by Th0masL** [comment]
For information, I've configured this option to make sure that it does not change anything for the users, unless they actually go in the settings and do enable the option.

So basically it's a transparent improvement. Only users that enable the option will see changes :-)

Thanks

**Comment by acicovic** [comment]
I'm also currently auto-generating usernames. Would be cool to see this in core!

**Comment by wp-insider** [comment]
Thank you. 

Does this work with the form builder addon? 
https://simple-membership-plugin.com/simple-membership-form-builder-addon/

If it doesn't then the actual functionality may need to be handled as an addon as opposed to a core plugin features (otherwise a lot of users will enable the feature and then ask us why it is not working with form builder and stuff like that).

**Comment by Th0masL** [comment]
Hi,

That is a good question.

I'm personally not using Form Builder, so I don't know yet.

I can spend some time testing those changes with form builder, but since Form Builder is a paid Add-on and since I don't need it, I don't plan to buy it, so the only way for me to test it would be if you send me a copy.

Is that possible ?

Thanks

Thomas

**Comment by Th0masL** [comment]
After thinking a bit more about this, I'm also totally fine to move this new functionality into a separate SWPM Add-on.

But in that case, I would still need to add couple of `apply_filters` to the files `add.php`, `edit.php` and `login.php`, or add some $variables (see below).

We could add an `apply_filters` line towards the top of the PHP files, in order to hook the Add-on before the form is loaded :

```
 <?php apply_filters('swpm_registration_form_top', ''); ?> // To add in add.php
 <?php apply_filters('swpm_edit_profile_form_top', ''); ?> // To add in edit.php
 <?php apply_filters('swpm_login_form_top', ''); ?> // To add in login.php
```

And we could add some `apply_filters` or simply a variable in the `<tr>` for the username properties :

```
// Example 1 : with adding a properties variable inside the <tr>
 <tr class="swpm-registration-username-row" <?php echo $swpm_registration_username_properties?>>
```
OR

```
// Example 2 : with adding an apply_filters inside the <tr>
 <tr class="swpm-registration-username-row" <?php apply_filters('swpm_registration_form_username_properties', ''); ?>>
```

Would you prefer this functionality to be in a separate Add-on ? And if so, which solution do you prefer, based on the example above ?

Thanks

Thomas

**Comment by wp-insider** [comment]
Thank you. Adding new filters is fine. Yes, I prefer it to be an addon. I think I like the 2nd example more.

**Comment by Th0masL** [comment]
Ok, then I will close this PR and create a new branch for adding the filters.

**Pull request closed without merging**
